<img src="Images/Information_Technology_University.png">
<h1><center>Assignment 1</center></h1>
<h2><center>Building an Information Retrieval System</center></h2>

<h4>Instructions:</h4>

- DO NOT PLAGIARISE

- Follow the instructions given in the code cells that are written in comments

- In case of any query, you can email at MSDS18008@itu.edu.pk

- Remember! We will enter a query and you should print the ranked list of document names

- Submit your Assignment in a zip file with your roll number as the file name. Like **"MSDS18008.zip"** 

In [1]:
#Improt the required Libraries
import os

In [2]:
#Reading the directory of our dataset of documents
files = os.listdir('data/')
files

['E93-1067.pdf.txt',
 'E89-1024.pdf.txt',
 'J06-2001.pdf.txt',
 'E14-1040.pdf.txt',
 'D08-1052.pdf.txt',
 'D12-1110.pdf.txt',
 'E12-1077.pdf.txt',
 'D15-1128.pdf.txt',
 'J05-3009.pdf.txt',
 'D15-1151.pdf.txt',
 'D08-1017.pdf.txt',
 'J03-1004.pdf.txt',
 'E14-4037.pdf.txt',
 'D14-1177.pdf.txt',
 'E95-1011.pdf.txt',
 'D11-1121.pdf.txt',
 'E99-1045.pdf.txt',
 'D15-1175.pdf.txt',
 'D15-1210.pdf.txt',
 'D14-1077.pdf.txt',
 'D15-1000.pdf.txt',
 'E03-1007.pdf.txt',
 'E97-1000.pdf.txt',
 'E14-1073.pdf.txt',
 'A88-1014.pdf.txt',
 'A94-1029.pdf.txt',
 'D13-1045.pdf.txt',
 'D13-1064.pdf.txt',
 'J06-2005.pdf.txt',
 'E14-1032.pdf.txt',
 'E12-1073.pdf.txt',
 'J04-4005.pdf.txt',
 'A97-1034.pdf.txt',
 'E09-1009.pdf.txt',
 'D14-1060.pdf.txt',
 'D14-1197.pdf.txt',
 'E03-1060.pdf.txt',
 'D15-1265.pdf.txt',
 'E83-1022.pdf.txt',
 'D11-1149.pdf.txt',
 'E06-1045.pdf.txt',
 'E97-1036.pdf.txt',
 'D09-1108.pdf.txt',
 'E14-1054.pdf.txt',
 'A83-1014.pdf.txt',
 'D13-1164.pdf.txt',
 'D13-1197.pdf.txt',
 'E97-1011.pd

In [3]:
# The following code takes all files, replaces new line character with space character and put words of all files in the Words list 
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
def read_files(files):
    Words = []
    for f in files:
        fhand = open("data/"+f,errors="ignore")
        file = fhand.read()
        file = file.replace("\n"," ") 
        file = file.replace(",","")
        file = file.replace("{","")
        file = file.replace("}","")
        file = file.replace("(","")
        file = file.replace(")","")    
        for word in file.split(" "):
            if word not in stop_words:
                Words.append(word)
    return Words        



In [4]:
Words=read_files(files)
Words[:100]

['Helyette:',
 'Inflectional',
 'Thesaurus',
 'Agglutinative',
 'Languages',
 '',
 'I',
 'MORPHOLOGE',
 '',
 '1=6',
 'u.',
 '56-58.',
 'I/3',
 '',
 'H-',
 '1011',
 'Budapest',
 '',
 'Hungary',
 '',
 'G~ibor',
 'Pr6$zP..ky',
 '12',
 '&',
 'I~szI6',
 'Tihalnyi',
 '',
 '\\]3',
 '',
 'OPKM',
 'COMP.',
 'CENTRE',
 '',
 'Honv~l',
 'u.',
 '19.',
 '',
 'H-',
 '1055',
 'Budapest',
 '',
 'Hungary',
 '',
 'e-mall:h6109pro@ella.hu',
 '',
 '1.',
 'Introduction',
 '',
 'In',
 'environment',
 'word-processors',
 'thesauri',
 'serve',
 '',
 "user's",
 'convenience',
 'choosing',
 'best',
 'suitable',
 'syno-',
 '',
 'nym',
 'word.',
 'Words',
 'text',
 'agglutinative',
 'languages',
 '',
 'occur',
 'almost',
 'always',
 'inflected',
 'forms',
 'thus',
 'finding',
 '',
 'directly',
 'stem',
 'vocabulary',
 'impossible.',
 'H01y0ltu',
 '',
 'inflectional',
 'thesaurus',
 'coping',
 'problem',
 '',
 'introduced',
 'paper.',
 '',
 '2.',
 'Synonym',
 'dictionary',
 '',
 'morphological',
 'knowledge',
 '',


In [5]:
#find count of unique words in all these files and store it in a dictionary
def word_count(Words):
    Word_To_Count = {}
    for w in Words:
        if w not in Word_To_Count:
            Word_To_Count[w]=1
        else:
            Word_To_Count[w]= Word_To_Count[w] + 1
    return Word_To_Count

In [6]:
Word_To_Count = word_count(Words)
dict_items = Word_To_Count.items()
list(dict_items)[:2] 


[('Helyette:', 3), ('Inflectional', 36)]

In [7]:
#print the count of Sweden
Word_To_Count["Sweden"]

402

In [8]:
def get_small_words(files):
    Small_Words = []
    for f in files:
        fhand = open("data/"+f,errors="ignore")
        file = fhand.read()
        file = file.replace("\n"," ")
        file = file.replace(",","")
        for word in file.split(" "):
            if word.isalpha():  # I WILL GET ONLY ALPHABETICAL DATA
                    if word.islower():
                        Small_Words.append(word.lower())
    return Small_Words  

In [9]:
#convert all text into lower case then find count of unique words,
lowercase =[v.lower() for v in Words] #str(Words).lower()
Small_Word_To_Count = word_count(lowercase)
print(Small_Word_To_Count["sweden"])
#read yueach file, split all words and append the lower case word in Small_Words list
Small_Words =get_small_words(files)

408


In [10]:
Small_Words[:10]

['for',
 'the',
 'environment',
 'of',
 'thesauri',
 'serve',
 'the',
 'convenience',
 'in',
 'choosing']

In [11]:
#Small_Words=Small_Words.replace('"',"")
#Small_Words = Small_Words.split('"')
print(Small_Words[:1])

['for']


In [12]:
#find count of unique words after converting them to lowercase in all these files and store it in a dictionary
Small_Word_To_Count = word_count(Small_Words)

    


In [13]:
dict_items = Small_Word_To_Count.items()

list(dict_items)[:2]

[('for', 180665), ('the', 809793)]

In [14]:
#sort the small words (in Small_Word_To_Count dictionary) by frequencies and store the results in freq.txt file
#Each line of the file should have word seperated by comma with its counts
#Hint: Can you use tuples to sort key value pairs in a list? (Explore Tuples by Yourself)
sorted_result = sorted(Small_Word_To_Count.items(), key=lambda x: x[1])
print(sorted_result[:2])
fhand = open("freq.txt",mode='w')
for word_freq in sorted_result:
    fhand.write(str(word_freq)+"\n")

[('tribune', 1), ('rrs', 1)]


In [15]:
#sort the words by alphabatical order and store results in words.txt file
#Each line of the file should have word seperated by comma with its counts
fhand = open("words.txt",mode='w')


sorted_result = dict(sorted(Word_To_Count.items()))

for word_freq in sorted_result:
    fhand.write(str(word_freq)+"\n")




In [16]:
# Sort the list of Small_Words alphabatically and store it in a new list called Vocabulary
# Vocabulary is the set of unique words
# Hint: Explore Set Function
d=sorted(Small_Words)
Vocabulary = list(set(d))
Vocabulary.sort()

In [17]:
print(d[:4])
print(Vocabulary[:4])

['a', 'a', 'a', 'a']
['a', 'aa', 'aaa', 'aaaa']


In [18]:
Vocabulary[-4]

'ʫ'

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(Vocabulary)
df.to_csv("r.csv")

In [21]:
# Now that the list (Vocabulary) is sorted alphabatically, 
# We can create dictionaries
import numpy as np
ID_list= np.arange(1,len(Vocabulary))
Word_to_ID = dict(zip(Vocabulary[:],ID_list))

In [22]:
Word_to_ID['є'] 

74557

In [23]:
# Now inverse the key value pairs of Word_to_ID Dictionary, so that we can search each word by its ID

    
ID_to_Word = dict(zip(ID_list,Vocabulary))#{v:k for k,v in Word_to_ID.items()}



In [24]:
ID_to_Word

{1: 'a',
 2: 'aa',
 3: 'aaa',
 4: 'aaaa',
 5: 'aaabbb',
 6: 'aaai',
 7: 'aaalyser',
 8: 'aaap',
 9: 'aab',
 10: 'aabb',
 11: 'aabbcc',
 12: 'aabbccdd',
 13: 'aabbcd',
 14: 'aach',
 15: 'aackendoff',
 16: 'aad',
 17: 'aada',
 18: 'aadcc',
 19: 'aadtr',
 20: 'aaedb',
 21: 'aagnant',
 22: 'aai',
 23: 'aaiti',
 24: 'aal',
 25: 'aalbessen',
 26: 'aame',
 27: 'aan',
 28: 'aanbieding',
 29: 'aand',
 30: 'aaneenges',
 31: 'aanknopingspunt',
 32: 'aantamiskokeet',
 33: 'aapl',
 34: 'aardvark',
 35: 'aarinen',
 36: 'aaron',
 37: 'aarp',
 38: 'aasoeiated',
 39: 'aastriche',
 40: 'aastriiche',
 41: 'aata',
 42: 'aatel',
 43: 'aaterlal',
 44: 'aavashyakataaen',
 45: 'aazut',
 46: 'ab',
 47: 'aba',
 48: 'abaa',
 49: 'abaaccbcb',
 50: 'abab',
 51: 'ababab',
 52: 'abaca',
 53: 'aback',
 54: 'abacus',
 55: 'abad',
 56: 'abaft',
 57: 'abalanced',
 58: 'abalistic',
 59: 'abalu',
 60: 'abama',
 61: 'abandon',
 62: 'abandoned',
 63: 'abandoning',
 64: 'abandonment',
 65: 'abandons',
 66: 'abarca',
 67: 'ab

In [25]:
Vocabulary=Vocabulary[:len(ID_to_Word)]

# An introduction to Sparse Matrix

A sparse matrix is a matrix that is comprised of mostly zero values.
Sparse matrices are distinct from matrices with mostly non-zero values, which are referred to as dense matrices.

"A matrix is sparse if many of its coefficients are zero. The interest in sparsity arises because its exploitation can lead to enormous computational savings and because many large matrix problems that occur in practice are sparse."

— Page 1, Direct Methods for Sparse Matrices, Second Edition, 2017.

Follwing is the example of a Sparse Matrix

<img src="Images/sparse_matrix.png" width="800" height="400">



## Problems with Sparsity

### Space Complexity
Very large matrices require a lot of memory, and some very large matrices that we wish to work with are sparse.
An example of a very large matrix that is too large to be stored in memory is a link matrix that shows the links from one website to another.

In this case, the matrix contained is sparse with many more zero values than data values. The problem with representing these sparse matrices as dense matrices is that memory is required and must be allocated for each 32-bit or even 64-bit zero value in the matrix.

This is clearly a waste of memory resources as those zero values do not contain any information.

### Time Complexity
Assuming a very large sparse matrix can be fit into memory, we will want to perform operations on this matrix.

Simply, if the matrix contains mostly zero-values, i.e. no data, then performing operations across this matrix may take a long time where the bulk of the computation performed will involve adding or multiplying zero values together.

##### Learn More About Sparse Matrrices on Internet. You have to work on sparse matrices in the following tasks

### Create the following Term Document Presence Matrix (Sparse Matrix)
<img src="Images/Document_Term.JPG" width="800" height="400">

The Matrix has shape **No of Documents X Vocabulary**

#### Read each document and save it in a Term Document matrix
#### The Size of document vector should be equal to the size of vocabulary


In [26]:
''' 
indptr =[0,len(matchdoc1),len(matchdoc1)+len(matchdoc2) ,len(matchdoc1)+len(matchdoc2)+len(matchdoc3),.... ]
i will use   this => sum = sum + len(matchdoci)
'''
sx  = 0 
indexes = []
word_frequency  = []



###### csr_matrix((data, indices, indptr1), shape=(len(files), len(Vocabulary))).toarray()   
###### get_freq is to collect informatiom in form of freq  for data 
###### get_indexes to collect information about indexes  for indices

In [27]:
def get_freq(doc_words,docs_invocab):
    global word_frequency
    Word_To_Count = {}
    for w in doc_words:
        if w in docs_invocab:
            if w not in Word_To_Count:
                Word_To_Count[w]=1
            else:
                Word_To_Count[w]= Word_To_Count[w] + 1
    d =(dict(sorted(Word_To_Count.items())))
    word_frequency= word_frequency + list(d.values())
    
    

In [28]:
def get_indexes(your_keys):
    try:
        global indexes
        dict_you_want = { your_key: Word_to_ID[your_key] for your_key in your_keys }
        indexes=indexes+ list(dict_you_want.values()) # dict_you_want.values() is consists of out indexes
    except Exception as e:
        print("[!]",e)
    return 0

In [29]:
#Your Code Here
def get_docvocab_matchedlist(filename): #this functionwill help me to build indptr list
    global sx
    documents_word = []
    fhand=open("data/"+filename,errors="ignore")
    file = fhand.read()
    file = file.replace("\n"," ")
    file = file.replace(",","")
    for word in file.split(" "):
        if word.isalpha():  # I WILL GET ONLY ALPHABETICAL DATA
                documents_word.append(word.lower())
    
    
    words_invocab = list(set(Vocabulary).intersection(set(documents_word)))
    words_invocab.sort()
    get_indexes(words_invocab)
    get_freq(documents_word,words_invocab)
    length = len(words_invocab)
    sx = sx + length    
    return sx

In [30]:
sx=0
indexes = []
word_frequency = []
indptr = list(map(get_docvocab_matchedlist,files))


In [31]:
indptr.insert(0,0)   
print(len(indexes))

res = [indptr[i + 1] - indptr[i] for i in range(len(indptr)-1)]

print ("The computed successive difference list is : " + str((sum(res))))


2911829
The computed successive difference list is : 2911829


In [32]:

import numpy as np
from scipy.sparse import csr_matrix,csc_matrix

indptr1 = np.array(indptr)
indices = np.array(indexes)
data = np.ones(len(indexes))
vector1= csr_matrix((data, indices, indptr1), shape=(len(files), len(Vocabulary))).toarray()
print(vector1)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


### Create the following Term Document Matrix Having Frequency of each word (Sparse Matrix)
<img src="Images/Term_Document_Frequency.JPG" width="800" height="400">


In [33]:
len(word_frequency)

2911829

In [34]:
indptr1 = np.array(indptr)
indices = np.array(indexes)
data = np.array(word_frequency)
vecor2=csr_matrix((data, indices, indptr1), shape=(len(files), len(Vocabulary))).toarray()

### Rank the documents using term frequncy matrix (Sparse Matrix)

In [37]:
def query_to_vector(Query):
        flag = False
        word_list  = Query.split()
        Query_Count = {}

        query_indexes = []
        try:
            for word in word_list:
                if word not in Query_Count:
                    Query_Count[word] = 1
                else:
                    Query_Count[word] = Query_Count[word] + 1
                if word in Vocabulary: 
                    flag = True
                    #print("yes >>>",word)
                    #print("yes >>>",Word_to_ID[word])
                    query_indexes.append(Word_to_ID[word])
                  
        except Exception as e:
            print("[!]",e)
        if flag==True:
            result = [flag,query_indexes,set(word_list),Query_Count]
            return result
        else:
            result = [flag]
            return result



In [38]:
flag = False
#Take Query from the User
Query = input("Enter the search Query: ")

#Convert the query into the query vector, This will be same as we converted each document into document vector

#print(len(set(word_list)),query_indexes)    

r = query_to_vector(Query) # returns [flag,query_indexes,set(word_list),Query_Count[word]

if r[0]:
    indptr1 = np.array([0,len(r[2])])
    indices = np.array(r[1])
    data = np.ones(len(r[1]))
    vector3=csc_matrix((data, indices, indptr1), shape=(len(Vocabulary),1)).toarray()        
    result1 = vector1.dot(vector3)
    r = [sum(i) for i in result1]
    top_5=np.argpartition(r, -4)[-4:]
    for file  in top_5:
        print(files[file])
else:
    print("OOPs! Nothing Matched")


Enter the search Query: a
A92-1007.pdf.txt
E06-2003.pdf.txt
D15-1070.pdf.txt
E91-1012.pdf.txt


In [39]:
'''
a = np.array([1, 2,3, 4, 5, 6, 7, 8, 9,10])
a
ind = np.argpartition(a, -4)[-4:]
ind
'''

'\na = np.array([1, 2,3, 4, 5, 6, 7, 8, 9,10])\na\nind = np.argpartition(a, -4)[-4:]\nind\n'

## Don't Forget the following things before proceeding further

* **You have to perform processing on Scipy Sparse Matrix (CSR or CSC)**
* **Try to explore the following**
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html
* **For further tasks you have to use the Term Documents matrix that has count of words**
* **Try to avoid for loops**
* **Don't plagiarise**

In [40]:
flag = False
#Take Query from the User
Query = input("Enter the search Query: ")
r = query_to_vector(Query) # returns [flag,query_indexes,set(word_list),Query_Count]

if r[0]:
    indptr1 = np.array([0,len(r[2])])
    indices = np.array(r[1])
    data = data = np.array(list(r[3].values()))

    vector3=csc_matrix((data, indices, indptr1), shape=(len(Vocabulary),1)).toarray()        
    result1 = vector1.dot(vector3)
    r = [sum(i) for i in result1]
    top_5=np.argpartition(r, -4)[-4:]
    for file  in top_5:
        print(files[file])
else:
    print("OOPs! Nothing Matched")


Enter the search Query: a
A92-1007.pdf.txt
E06-2003.pdf.txt
D15-1070.pdf.txt
E91-1012.pdf.txt


<h3><center>Remember: The only help you need is in your lab notebooks and Internet<h3>

In [ ]:
!pip install scipy


In [ ]:
import numpy as np
from scipy.sparse import csr_matrix

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, indices, indptr), shape=(3, 3)).ceil()

In [ ]:
mydict = {'carl':40,
          'alan':2,
          'bob':1,
          'danny':3}
dict(sorted(mydict.items()))
mydict.get(['carl',["bob"]])

In [ ]:
a= ["aa","ab"]
sorted(a)
print(a)

In [ ]:
a = np.array([[1, 2], [3, 4], [3, 5], [4, 1], [4, 6]])
b = np.array([[3, 4], [4, 6]])

a1_rows = a.view([('', a.dtype)] * a.shape[1])
a2_rows = b.view([('', b.dtype)] * b.shape[1])
c = np.setdiff1d(a1_rows, a2_rows).view(a.dtype).reshape(-1, a.shape[1])
print (c)


In [ ]:

a=[2]
b=[4]

a.extend([3,4])
a

In [ ]:
list1 = ['red', 'green', 'blue', 'orange', 'green', 'gray', 'green']
color_count = list1.count('blue')
print('The count of color: green is ', color_count)
list(set(list1))
list2=["blue","green"]
#list1 = [1,2,3,4,5,6]
#list2 = [3, 5, 7, 9]
list(set(list1).intersection(set(list2))


In [ ]:
z=[('a', 1), ('above', 261)]
dict(z)